# Generated by Django 5.0.2 on 2025-06-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_restore', '0002_photorestore_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photorestore',
            name='restored_image',
            field=models.ImageField(blank=True, null=True, upload_to='restored/'),
        ),
        migrations.AlterField(
            model_name='photorestore',
            name='restored_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
